### ISSUE TITLE
Review Microtasks

### ISSUE THREAD

**Issue by vchrombie** [SteveKola/grimoirelab-microtasks#1]
Hi @SteveKola, thanks for showing interest in applying for the GrimoireLab idea and working on the microtasks as a part of the GSoC program.

You can open an issue per microtask with the title `Review Microtask <num>` in this repository. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask. I can help with reviewing the microtasks and suggest some improvements.

Thanks!

**Comment by SteveKola** [comment]
Thank you, @vchrombie. 😄 
I'm curious, though. How did you find this repository?

**Comment by vchrombie** [comment]
>  I'm curious, though. How did you find this repository?

It was always on your github profile :wink:

**Comment by SteveKola** [comment]
Lol... Thank you, once agian.
I'll do as you suggested.

**Comment by vchrombie** [comment]
Thanks for working on the microtasks, please make sure you submit the proposal on the GSoC website as well as add your entry in the governance repository before the deadline.

**Comment by vchrombie** [comment]
I think we can close this issue.
