### ISSUE TITLE
Review microtask 10

### ISSUE THREAD

**Issue by stevenkolawole** [SteveKola/grimoirelab-microtasks#10]
[https://github.com/SteveKola/grimoirelab-microtasks/tree/main/microtask10](https://github.com/SteveKola/grimoirelab-microtasks/tree/main/microtask10)

WDYT, @vchrombie?

**Comment by vchrombie** [comment]
LGTM, please feel free to keep updating the list if you have any new PRs.

**Comment by SteveKola** [comment]
Alright, I will.
