### ISSUE TITLE
Mysql_config not found, while using `Poetry install` on SortingHat

### ISSUE THREAD

**Issue by stevenkolawole** [SteveKola/grimoirelab-microtasks#5]
I'm not sure if I should create this issue here or on SortingHat's repository, but while setting up the environment for SortingHat, I did `poetry install` and I got this error.

``` 
 • Installing mysqlclient (1.3.13): Failed
  EnvCommandError
...
      OSError: mysql_config not found
```
What could possibly be wrong?

**cc:** @sduenas @vchrombie

**Comment by SteveKola** [comment]
Never mind. I've sorted it out.

Apparently, one needs to install `mysql_config` command by installing `libmysqlclient-dev` or `libmariadbclient-dev` (depending on which of the database servers is being used.

I installed `libmariadbclient-dev` initially. When I installed `libmysqlclient-dev`, it installed properly.
