### ISSUE TITLE
Review Microtask 5

### ISSUE THREAD

**Issue by SteveKola** [SteveKola/grimoirelab-microtasks#7]
[https://github.com/SteveKola/grimoirelab-microtasks/tree/main/microtask5](https://github.com/SteveKola/grimoirelab-microtasks/tree/main/microtask5)

What do you think, @vchrombie?

**Comment by vchrombie** [comment]
Hi @SteveKola, I checked the microtask and I have some feedback on it.

The task is to create a sample profile with different identities and enrollments using the SortingHat UI. 

![](https://camo.githubusercontent.com/fec2b15524b667a45322d15205bb09b1fad3f2c43a29048ea36417bbc8985eb9/68747470733a2f2f69302e77702e636f6d2f626c6f672e62697465726769612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30322f736f7274696e676861742d6d756c7469706c652d6964656e7469746965732d657861706c652e706e673f726573697a653d3736382532433434382673736c3d31)

But, I see 9 different identities of the same individual. I think you forgot some steps or you haven't updated the task. Can you please have a look at it when you are free.

**Comment by SteveKola** [comment]
My mistake. :(
I think I've fixed it now. Thank you for calling my attention to it.

**Comment by vchrombie** [comment]
LGTM
